//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nintex.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWClientURL
    {
        public string Name { get; set; }
        public int ClientId { get; set; }
        public string LongURL { get; set; }
        public string ShortURL { get; set; }
        public string LoginId { get; set; }
        public int UrlId { get; set; }
        public int ClientCount { get; set; }
    }
}
